version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    container_name: minio_container
    networks:
      - minionetwork
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DEFAULT_BUCKETS: ${MINIO_BUCKET}
    command: server /data --console-address ":9001"

    ports:
      - "${MINIO_PORT}:9000"
      - "${MINIO_PORT_ADMIN}:9001"
    volumes:
      - minio_data:/data

networks:
  minionetwork:
    driver: bridge

volumes:
  db_data:
  minio_data:
    driver: local