export enum BodyPart {
  WAIST = 'waist',
  UPPER_LEGS = 'upper legs',
  BACK = 'back',
  LOWER_LEGS = 'lower legs',
  CHEST = 'chest',
  UPPER_ARMS = 'upper arms',
  CARDIO = 'cardio',
  SHOULDERS = 'shoulders',
  LOWER_ARMS = 'lower arms',
  NECK = 'neck',
}

export enum EquipmentType {
  BODY_WEIGHT = 'body weight',
  CABLE = 'cable',
  LEVERAGE_MACHINE = 'leverage machine',
  ASSISTED = 'assisted',
  MEDICINE_BALL = 'medicine ball',
  STABILITY_BALL = 'stability ball',
  BAND = 'band',
  BARBELL = 'barbell',
  ROPE = 'rope',
  DUMBBELL = 'dumbbell',
  EZ_BARBELL = 'ez barbell',
  SLED_MACHINE = 'sled machine',
  UPPER_BODY_ERGOMETER = 'upper body ergometer',
  KETTLEBELL = 'kettlebell',
  OLYMPIC_BARBELL = 'olympic barbell',
  WEIGHTED = 'weighted',
  BOSU_BALL = 'bosu ball',
  RESISTANCE_BAND = 'resistance band',
  ROLLER = 'roller',
  SKIERG_MACHINE = 'skierg machine',
  HAMMER = 'hammer',
  SMITH_MACHINE = 'smith machine',
  WHEEL_ROLLER = 'wheel roller',
  STATIONARY_BIKE = 'stationary bike',
  TIRE = 'tire',
  TRAP_BAR = 'trap bar',
  ELLIPTICAL_MACHINE = 'elliptical machine',
  STEPMILL_MACHINE = 'stepmill machine',
}
